export const ADD_POKEMON = "ADD_POKEMFETCH_POKEMON_SUCCESSON_ACTION";
export const USER_NAVIGATION = "NAVIGATION_ACTION";
export const ADD_POKEMON_LIST = "ADD_POKEMON_LIST";
export const USER_TYPE = "USER_TYPE";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_START = "FETCH_POKEMON_START"; 
export const FETCH_POKEMON_FAILURE = "FETCH_POKEMON_FAILURE";